#!/bin/sh

RED="31"
GREEN="32"
BOLDGREEN="\e[1;${GREEN}m"
ITALICRED="\e[3;${RED}m"
ENDCOLOR="\e[0m"

if [ -z "$1" ]
then
  echo -e "${RED}The name(plural) attribute should be provided, eg: ./gen brands${NOCOLOR}"
else
  echo -e "${BOLDGREEN}Generating api resources(API)${NOCOLOR}"
  cd packages/api && schematics @vp/genom:resource $1
  cd ../..
  echo -e "${BOLDGREEN}Generating crud yup schemas(Common)${NOCOLOR}"
  cd packages/common && schematics @vp/genom:schema $1
  cd ../..
  echo -e "${BOLDGREEN}Building the common package(Common)${NOCOLOR}"
  yarn common:build
  echo -e "${BOLDGREEN}Generating graphql resources(WEB)${NOCOLOR}"
  cd packages/web && schematics @vp/genom:graphql $1
  cd ../..
  echo -e "${BOLDGREEN}Generating graphql client hooks(WEB)${NOCOLOR}"
  yarn web:gen
  echo -e "${BOLDGREEN}Generating the page(WEB)${NOCOLOR}"
  cd packages/web && schematics @vp/genom:page $1
  cd ../..
fi
